# Generated by Django 6.0.5 on 2026-05-27 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="bases/")),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-enviado_em"],
            },
        ),
        migrations.CreateModel(
            name="ResultadoRegressao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "servico",
                    models.CharField(
                        choices=[
                            ("expansao", "Expansão"),
                            ("formatacao", "Formatação"),
                            ("validacao", "Validação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("calculado_em", models.DateTimeField(auto_now_add=True)),
                ("beta0", models.FloatField()),
                ("beta1", models.FloatField()),
                ("beta2", models.FloatField()),
                ("beta3", models.FloatField()),
                ("beta4", models.FloatField(blank=True, null=True)),
                ("r2", models.FloatField()),
                ("r2_ajustado", models.FloatField()),
                ("mae", models.FloatField()),
                ("elasticidades", models.JSONField(default=dict)),
                ("custo_por_contrato", models.FloatField()),
                ("preco_ideal_30", models.FloatField()),
                ("margem_observada", models.FloatField()),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="app.uploadedbase",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculado_em"],
            },
        ),
    ]
